
MODLIST = lndpm lndcal lndsr lndapp lndsrbm 6sV-1.0B

all:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static) \
	done

install:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static install) \
	done

clean:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static clean > /dev/null) \
	done
