
MODLIST = lndpm lndcal lndsr lndsrbm 6sV-1.0B

all:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static; cd ..) \
	done

install:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static install; cd ..) \
	done

clean:
	@for i in $(MODLIST); do \
	(cd $$i; make -f Makefile.static clean; cd ..) \
	done
